import type { GlobalConfig } from "payload";

export const AboutPage: GlobalConfig = {
  slug: "about-page",
  label: { en: "About Page", tr: "Hakkımızda Sayfası" },
  access: { read: () => true },
  admin: { group: { en: "Pages", tr: "Sayfalar" } },
  fields: [
    {
      name: "eyebrow",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Eyebrow", tr: "Üst etiket" },
    },
    {
      name: "pageTitle",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Page title", tr: "Sayfa başlığı" },
    },
    {
      name: "pageTitleHighlight",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Title highlight", tr: "Vurgulu kelime" },
    },
    {
      name: "pageTitleSuffix",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Title suffix", tr: "Başlık soneki" },
    },
    {
      name: "pageDescription",
      type: "textarea",
      required: true,
      localized: true,
      label: { en: "Page description", tr: "Sayfa açıklaması" },
    },
    {
      name: "experienceLabel",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Experience label", tr: "Deneyim etiketi" },
    },
    // ==================== HERO STATS ====================
    {
      name: "heroStats",
      type: "group",
      label: { en: "Hero stats", tr: "Hero istatistikleri" },
      fields: [
        {
          name: "foundedLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Founded label", tr: "Kuruluş etiketi" },
        },
        {
          name: "foundedValue",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Founded value", tr: "Kuruluş değeri" },
        },
        {
          name: "teamLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Team label", tr: "Ekip etiketi" },
        },
        {
          name: "teamValue",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Team value", tr: "Ekip değeri" },
        },
        {
          name: "projectsLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Projects label", tr: "Projeler etiketi" },
        },
        {
          name: "projectsValue",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Projects value", tr: "Projeler değeri" },
        },
        {
          name: "citiesLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Cities label", tr: "Şehir etiketi" },
        },
        {
          name: "citiesValue",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Cities value", tr: "Şehir değeri" },
        },
      ],
    },
    // ==================== MANIFESTO ====================
    {
      name: "manifesto",
      type: "group",
      label: { en: "Manifesto", tr: "Manifesto" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "line1",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 1", tr: "Satır 1" },
        },
        {
          name: "line2",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 2", tr: "Satır 2" },
        },
        {
          name: "line3",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 3", tr: "Satır 3" },
        },
        {
          name: "line4",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 4", tr: "Satır 4" },
        },
        {
          name: "line5",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 5 (highlight)", tr: "Satır 5 (vurgulu)" },
        },
        {
          name: "line6",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 6", tr: "Satır 6" },
        },
        {
          name: "line7",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 7", tr: "Satır 7" },
        },
        {
          name: "line8",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Line 8 (highlight)", tr: "Satır 8 (vurgulu)" },
        },
      ],
    },
    // ==================== STORY ====================
    {
      name: "story",
      type: "group",
      label: { en: "Story", tr: "Hikâye" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "body1",
          type: "textarea",
          required: true,
          localized: true,
          admin: { description: "HTML destekli (strong vb.)" },
          label: { en: "Body paragraph 1", tr: "Paragraf 1" },
        },
        {
          name: "body2",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Body paragraph 2", tr: "Paragraf 2" },
        },
        {
          name: "body3",
          type: "textarea",
          required: true,
          localized: true,
          admin: { description: "HTML destekli (strong vb.)" },
          label: { en: "Body paragraph 3", tr: "Paragraf 3" },
        },
        {
          name: "caption",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Caption", tr: "Alt yazı" },
        },
      ],
    },
    // ==================== TIMELINE ====================
    {
      name: "timeline",
      type: "group",
      label: { en: "Timeline", tr: "Zaman çizelgesi" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Timeline items", tr: "Zaman çizelgesi öğeleri" },
          fields: [
            {
              name: "year",
              type: "text",
              required: true,
              label: { en: "Year", tr: "Yıl" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "text",
              type: "textarea",
              required: true,
              label: { en: "Text", tr: "Metin" },
            },
          ],
        },
      ],
    },
    // ==================== TEAM ====================
    {
      name: "team",
      type: "group",
      label: { en: "Team block", tr: "Ekip bloğu" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
      ],
    },
    // ==================== VALUES ====================
    {
      name: "values",
      type: "group",
      label: { en: "Values", tr: "Değerler" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          admin: {
            description: "4 items — keys: care, transparency, speed, human",
          },
          label: { en: "Value items (4)", tr: "Değer öğeleri (4)" },
          fields: [
            {
              name: "key",
              type: "select",
              required: true,
              options: [
                { label: "care", value: "care" },
                { label: "transparency", value: "transparency" },
                { label: "speed", value: "speed" },
                { label: "human", value: "human" },
              ],
              label: { en: "Key", tr: "Anahtar" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "text",
              type: "textarea",
              required: true,
              label: { en: "Text", tr: "Metin" },
            },
          ],
        },
      ],
    },
    // ==================== BIG STATS ====================
    {
      name: "bigStats",
      type: "group",
      label: { en: "Big stats", tr: "Büyük istatistikler" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Big stat items", tr: "Büyük istatistik öğeleri" },
          fields: [
            {
              name: "value",
              type: "number",
              required: true,
              label: { en: "Value", tr: "Değer" },
            },
            {
              name: "suffix",
              type: "text",
              required: false,
              label: { en: "Suffix", tr: "Sonek" },
            },
            {
              name: "decimals",
              type: "number",
              required: false,
              label: { en: "Decimals", tr: "Ondalık" },
            },
            {
              name: "label",
              type: "text",
              required: true,
              label: { en: "Label", tr: "Etiket" },
            },
          ],
        },
      ],
    },
  ],
};
