import type { GlobalConfig } from "payload";

export const ContactPage: GlobalConfig = {
  slug: "contact-page",
  label: { en: "Contact Page", tr: "İletişim Sayfası" },
  access: { read: () => true },
  admin: { group: { en: "Pages", tr: "Sayfalar" } },
  fields: [
    {
      name: "pageTitle",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Page title", tr: "Sayfa başlığı" },
    },
    {
      name: "pageTitleHighlight",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Title highlight", tr: "Vurgulu kelime" },
    },
    {
      name: "pageTitleSuffix",
      type: "text",
      required: true,
      localized: true,
      label: { en: "Title suffix", tr: "Başlık soneki" },
    },
    {
      name: "pageDescription",
      type: "textarea",
      required: true,
      localized: true,
      label: { en: "Page description", tr: "Sayfa açıklaması" },
    },
    // ==================== LABELS ====================
    {
      name: "labels",
      type: "group",
      label: { en: "Labels", tr: "Etiketler" },
      fields: [
        {
          name: "whatsapp",
          type: "text",
          required: true,
          localized: true,
          label: { en: "WhatsApp", tr: "WhatsApp" },
        },
        {
          name: "email",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Email", tr: "E-posta" },
        },
        {
          name: "phone",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Phone", tr: "Telefon" },
        },
        {
          name: "office",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Office", tr: "Ofis" },
        },
        {
          name: "hours",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Hours", tr: "Saatler" },
        },
        {
          name: "social",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Social", tr: "Sosyal" },
        },
      ],
    },
    // ==================== VALUES ====================
    {
      name: "values",
      type: "group",
      label: { en: "Values", tr: "Değerler" },
      fields: [
        {
          name: "office",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Office", tr: "Ofis" },
        },
        {
          name: "hours",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Hours", tr: "Saatler" },
        },
      ],
    },
    // ==================== FORM ====================
    {
      name: "form",
      type: "group",
      label: { en: "Form", tr: "Form" },
      fields: [
        {
          name: "name",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Name label", tr: "Ad etiketi" },
        },
        {
          name: "namePlaceholder",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Name placeholder", tr: "Ad yer tutucu" },
        },
        {
          name: "email",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Email label", tr: "E-posta etiketi" },
        },
        {
          name: "emailPlaceholder",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Email placeholder", tr: "E-posta yer tutucu" },
        },
        {
          name: "company",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Company label", tr: "Şirket etiketi" },
        },
        {
          name: "companyPlaceholder",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Company placeholder", tr: "Şirket yer tutucu" },
        },
        {
          name: "phone",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Phone label", tr: "Telefon etiketi" },
        },
        {
          name: "phonePlaceholder",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Phone placeholder", tr: "Telefon yer tutucu" },
        },
        {
          name: "service",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Service label", tr: "Hizmet etiketi" },
        },
        {
          name: "message",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Message label", tr: "Mesaj etiketi" },
        },
        {
          name: "messagePlaceholder",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Message placeholder", tr: "Mesaj yer tutucu" },
        },
        {
          name: "submit",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Submit", tr: "Gönder" },
        },
        {
          name: "privacy",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Privacy", tr: "Gizlilik" },
        },
        {
          name: "services",
          type: "array",
          localized: true,
          label: { en: "Service options", tr: "Hizmet seçenekleri" },
          fields: [
            {
              name: "label",
              type: "text",
              required: true,
              label: { en: "Label", tr: "Etiket" },
            },
          ],
        },
        {
          name: "successTitle",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Success title", tr: "Başarı başlığı" },
        },
        {
          name: "successMessage",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Success message", tr: "Başarı mesajı" },
        },
      ],
    },
  ],
};
