import type { GlobalConfig } from "payload";

export const HomePage: GlobalConfig = {
  slug: "home-page",
  label: { en: "Home Page", tr: "Ana Sayfa" },
  access: { read: () => true },
  admin: { group: { en: "Pages", tr: "Sayfalar" } },
  fields: [
    // ==================== HERO ====================
    {
      name: "hero",
      type: "group",
      label: { en: "Hero", tr: "Hero" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "socialProof",
          type: "textarea",
          required: true,
          localized: true,
          admin: { description: "HTML destekli (strong vb.)" },
          label: { en: "Social proof", tr: "Sosyal kanıt" },
        },
        {
          name: "title1",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title line 1", tr: "Başlık satır 1" },
        },
        {
          name: "title2",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title line 2", tr: "Başlık satır 2" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "primaryCta",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Primary CTA label", tr: "Birincil CTA etiketi" },
        },
        {
          name: "primaryCtaHref",
          type: "text",
          required: true,
          defaultValue: "/contact",
          label: { en: "Primary CTA link", tr: "Birincil CTA bağlantısı" },
        },
        {
          name: "secondaryCta",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Secondary CTA label", tr: "İkincil CTA etiketi" },
        },
        {
          name: "secondaryCtaHref",
          type: "text",
          required: true,
          defaultValue: "/work",
          label: { en: "Secondary CTA link", tr: "İkincil CTA bağlantısı" },
        },
        {
          name: "scrollHint",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Scroll hint", tr: "Kaydırma ipucu" },
        },
        {
          name: "chips",
          type: "array",
          localized: true,
          label: { en: "Floating chips (4)", tr: "Yüzen çipler (4)" },
          admin: {
            description: "Sırayla: shopify, metaAds, tiktok, ai",
          },
          fields: [
            {
              name: "label",
              type: "text",
              required: true,
              label: { en: "Label", tr: "Etiket" },
            },
          ],
        },
      ],
    },
    // ==================== STATS ====================
    {
      name: "stats",
      type: "group",
      label: { en: "Hero Stats", tr: "Hero İstatistikleri" },
      fields: [
        {
          name: "revenueLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Revenue label", tr: "Ciro etiketi" },
        },
        {
          name: "revenueValue",
          type: "text",
          required: true,
          defaultValue: "312%",
          label: { en: "Revenue value", tr: "Ciro değeri" },
        },
        {
          name: "roasLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "ROAS label", tr: "ROAS etiketi" },
        },
        {
          name: "roasValue",
          type: "text",
          required: true,
          defaultValue: "5.4x",
          label: { en: "ROAS value", tr: "ROAS değeri" },
        },
        {
          name: "brandsLabel",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Brands label", tr: "Marka etiketi" },
        },
        {
          name: "brandsValue",
          type: "text",
          required: true,
          defaultValue: "120+",
          label: { en: "Brands value", tr: "Marka değeri" },
        },
      ],
    },
    // ============= STATS STRIP (4'lü şerit) =============
    {
      name: "statsStrip",
      type: "array",
      localized: true,
      label: { en: "Stats strip (4)", tr: "İstatistik şeridi (4)" },
      admin: {
        description:
          "Hizmetler bölümünün altındaki 4'lü büyük rakam şeridi. Sırayı koru.",
      },
      minRows: 0,
      maxRows: 4,
      fields: [
        {
          name: "value",
          type: "text",
          required: true,
          label: { en: "Value", tr: "Değer" },
          admin: { description: "ör: 120+, 8, 4.9/5, 32M+" },
        },
        {
          name: "label",
          type: "text",
          required: true,
          label: { en: "Label", tr: "Etiket" },
        },
      ],
    },
    // ==================== MARQUEE ====================
    {
      name: "marquee",
      type: "group",
      label: { en: "Marquee", tr: "Logo Akışı" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
      ],
    },
    // ==================== SECTIONS ====================
    {
      name: "sections",
      type: "group",
      label: { en: "Sections", tr: "Bölümler" },
      fields: [
        {
          name: "services",
          type: "group",
          label: { en: "Services block", tr: "Hizmetler bloğu" },
          fields: [
            {
              name: "eyebrow",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Eyebrow", tr: "Üst etiket" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "titleHighlight",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title highlight", tr: "Vurgulu kelime" },
            },
            {
              name: "description",
              type: "textarea",
              required: true,
              localized: true,
              label: { en: "Description", tr: "Açıklama" },
            },
          ],
        },
        {
          name: "projects",
          type: "group",
          label: { en: "Projects block", tr: "Projeler bloğu" },
          fields: [
            {
              name: "eyebrow",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Eyebrow", tr: "Üst etiket" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "titleHighlight",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title highlight", tr: "Vurgulu kelime" },
            },
            {
              name: "description",
              type: "textarea",
              required: true,
              localized: true,
              label: { en: "Description", tr: "Açıklama" },
            },
            {
              name: "cta",
              type: "text",
              required: true,
              localized: true,
              label: { en: "CTA label", tr: "CTA etiketi" },
            },
          ],
        },
        {
          name: "process",
          type: "group",
          label: { en: "Process block", tr: "Süreç bloğu" },
          fields: [
            {
              name: "eyebrow",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Eyebrow", tr: "Üst etiket" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "titleHighlight",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title highlight", tr: "Vurgulu kelime" },
            },
            {
              name: "description",
              type: "textarea",
              required: true,
              localized: true,
              label: { en: "Description", tr: "Açıklama" },
            },
            {
              name: "steps",
              type: "array",
              localized: true,
              label: { en: "Steps (4)", tr: "Adımlar (4)" },
              admin: {
                description: "Sürecin 4 adımı. Sıra korunur (01–04).",
              },
              minRows: 0,
              maxRows: 4,
              fields: [
                {
                  name: "title",
                  type: "text",
                  required: true,
                  label: { en: "Title", tr: "Başlık" },
                },
                {
                  name: "text",
                  type: "textarea",
                  required: true,
                  label: { en: "Text", tr: "Metin" },
                },
              ],
            },
          ],
        },
        {
          name: "testimonials",
          type: "group",
          label: { en: "Testimonials block", tr: "Referanslar bloğu" },
          fields: [
            {
              name: "eyebrow",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Eyebrow", tr: "Üst etiket" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "titleHighlight",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title highlight", tr: "Vurgulu kelime" },
            },
          ],
        },
        {
          name: "loomTeaser",
          type: "group",
          label: { en: "Loom teaser block", tr: "Loom teaser bloğu" },
          fields: [
            {
              name: "eyebrow",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Eyebrow", tr: "Üst etiket" },
            },
            {
              name: "title",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "titleHighlight",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title highlight", tr: "Vurgulu kelimeler" },
            },
            {
              name: "titleSuffix",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Title suffix", tr: "Başlık soneki" },
            },
            {
              name: "description",
              type: "textarea",
              required: true,
              localized: true,
              label: { en: "Description", tr: "Açıklama" },
            },
            {
              name: "modulesLabel",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Modules label", tr: "Modüller etiketi" },
            },
            {
              name: "learnMore",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Learn more CTA", tr: "Keşfet CTA" },
            },
            {
              name: "pilotBadge",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Pilot badge", tr: "Pilot rozeti" },
            },
            {
              name: "chips",
              type: "array",
              localized: true,
              label: { en: "Chips", tr: "Çipler" },
              fields: [
                {
                  name: "label",
                  type: "text",
                  required: true,
                  label: { en: "Label", tr: "Etiket" },
                },
              ],
            },
            {
              name: "modules",
              type: "array",
              localized: true,
              label: { en: "Modules (5)", tr: "Modüller (5)" },
              fields: [
                {
                  name: "name",
                  type: "text",
                  required: true,
                  label: { en: "Name", tr: "Ad" },
                },
                {
                  name: "subtitle",
                  type: "text",
                  required: true,
                  label: { en: "Subtitle", tr: "Altbaşlık" },
                },
                {
                  name: "hint",
                  type: "text",
                  required: true,
                  label: { en: "Hint", tr: "İpucu" },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
