import type { GlobalConfig } from "payload";

export const LoomPage: GlobalConfig = {
  slug: "loom-page",
  label: { en: "Loom Page", tr: "Loom Sayfası" },
  access: { read: () => true },
  admin: { group: { en: "Pages", tr: "Sayfalar" } },
  fields: [
    // ==================== META ====================
    {
      name: "meta",
      type: "group",
      label: { en: "Meta", tr: "Meta" },
      fields: [
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Meta title", tr: "Meta başlık" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Meta description", tr: "Meta açıklama" },
        },
      ],
    },
    // ==================== HERO ====================
    {
      name: "hero",
      type: "group",
      label: { en: "Hero", tr: "Hero" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "brand",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Brand", tr: "Marka" },
        },
        {
          name: "tagline",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Tagline", tr: "Slogan" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          admin: { description: "HTML destekli (strong vb.)" },
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "primaryCta",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Primary CTA", tr: "Birincil CTA" },
        },
        {
          name: "secondaryCta",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Secondary CTA", tr: "İkincil CTA" },
        },
        {
          name: "badge",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Badge", tr: "Rozet" },
        },
      ],
    },
    // ==================== PROBLEM ====================
    {
      name: "problem",
      type: "group",
      label: { en: "Problem", tr: "Sorun" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Problem items", tr: "Sorun öğeleri" },
          fields: [
            {
              name: "title",
              type: "text",
              required: true,
              label: { en: "Title", tr: "Başlık" },
            },
            {
              name: "text",
              type: "textarea",
              required: true,
              label: { en: "Text", tr: "Metin" },
            },
          ],
        },
        {
          name: "closing",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Closing paragraph", tr: "Kapanış paragrafı" },
        },
      ],
    },
    // ==================== MODULES ====================
    {
      name: "modules",
      type: "group",
      label: { en: "Modules", tr: "Modüller" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Modules (5)", tr: "Modüller (5)" },
          fields: [
            {
              name: "code",
              type: "text",
              required: true,
              label: { en: "Code", tr: "Kod" },
            },
            {
              name: "name",
              type: "text",
              required: true,
              label: { en: "Name", tr: "Ad" },
            },
            {
              name: "subtitle",
              type: "text",
              required: true,
              label: { en: "Subtitle", tr: "Altbaşlık" },
            },
            {
              name: "description",
              type: "textarea",
              required: true,
              label: { en: "Description", tr: "Açıklama" },
            },
            {
              name: "example",
              type: "text",
              required: true,
              label: { en: "Example", tr: "Örnek" },
            },
          ],
        },
      ],
    },
    // ==================== COMPARISON ====================
    {
      name: "comparison",
      type: "group",
      label: { en: "Comparison", tr: "Karşılaştırma" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "headers",
          type: "group",
          label: { en: "Headers", tr: "Başlıklar" },
          fields: [
            {
              name: "dim",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Dimension", tr: "Boyut" },
            },
            {
              name: "agency",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Agency", tr: "Ajans" },
            },
            {
              name: "loom",
              type: "text",
              required: true,
              localized: true,
              label: { en: "Loom", tr: "Loom" },
            },
          ],
        },
        {
          name: "rows",
          type: "array",
          localized: true,
          label: { en: "Rows", tr: "Satırlar" },
          fields: [
            {
              name: "label",
              type: "text",
              required: true,
              label: { en: "Label", tr: "Etiket" },
            },
            {
              name: "agency",
              type: "text",
              required: true,
              label: { en: "Agency", tr: "Ajans" },
            },
            {
              name: "loom",
              type: "text",
              required: true,
              label: { en: "Loom", tr: "Loom" },
            },
          ],
        },
      ],
    },
    // ==================== TECH ====================
    {
      name: "tech",
      type: "group",
      label: { en: "Tech", tr: "Teknoloji" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Tech items", tr: "Teknoloji öğeleri" },
          fields: [
            {
              name: "name",
              type: "text",
              required: true,
              label: { en: "Name", tr: "Ad" },
            },
            {
              name: "desc",
              type: "textarea",
              required: true,
              label: { en: "Description", tr: "Açıklama" },
            },
          ],
        },
      ],
    },
    // ==================== TARGET ====================
    {
      name: "target",
      type: "group",
      label: { en: "Target", tr: "Hedef kitle" },
      fields: [
        {
          name: "eyebrow",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Eyebrow", tr: "Üst etiket" },
        },
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "items",
          type: "array",
          localized: true,
          label: { en: "Target items", tr: "Hedef öğeleri" },
          fields: [
            {
              name: "text",
              type: "text",
              required: true,
              label: { en: "Text", tr: "Metin" },
            },
          ],
        },
        {
          name: "closing",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Closing", tr: "Kapanış" },
        },
      ],
    },
    // ==================== CTA ====================
    {
      name: "cta",
      type: "group",
      label: { en: "CTA", tr: "CTA" },
      fields: [
        {
          name: "title",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title", tr: "Başlık" },
        },
        {
          name: "titleHighlight",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title highlight", tr: "Vurgulu kelime" },
        },
        {
          name: "titleSuffix",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Title suffix", tr: "Başlık soneki" },
        },
        {
          name: "description",
          type: "textarea",
          required: true,
          localized: true,
          label: { en: "Description", tr: "Açıklama" },
        },
        {
          name: "primary",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Primary CTA", tr: "Birincil CTA" },
        },
        {
          name: "email",
          type: "text",
          required: true,
          defaultValue: "hello@loom.co",
          label: { en: "Email", tr: "E-posta" },
        },
        {
          name: "web",
          type: "text",
          required: true,
          defaultValue: "loom.co",
          label: { en: "Web", tr: "Web" },
        },
        {
          name: "guarantee",
          type: "text",
          required: true,
          localized: true,
          label: { en: "Guarantee", tr: "Garanti" },
        },
      ],
    },
  ],
};
